name: deploy
on:
  push:
    branches:
      - development

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

jobs:
  deploy:
    name: sample-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: deploy
        run: bash deploy.sh ${{ secrets.MYSQL_ROOT_PASSWORD }}
